# Generated by Django 2.0.4 on 2018-04-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ariphmetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='answer',
            name='dt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ariphmetics.Question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_int',
            field=models.IntegerField(default=0),
        ),
    ]
